import React from "react";
import { View, StyleSheet, ScrollView, Pressable } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { Feather } from "@expo/vector-icons";
import { useRouter } from "expo-router";

import { Txt } from "@/src/components/ui";
import { colors, spacing, fontSize } from "@/src/theme/theme";

// ✅ Placeholders filled in (Rohan Khanna, rohankhanna1992@gmail.com), and a
// real "Delete My Data" feature now exists (Care tab). Still worth a real
// attorney's review before this goes in front of Apple or real users,
// given the health, location, and demographic data this app handles.

function H2({ children }: { children: string }) {
  return <Txt display style={styles.h2}>{children}</Txt>;
}
function P({ children }: { children: React.ReactNode }) {
  return <Txt style={styles.p}>{children}</Txt>;
}
function Placeholder({ children }: { children: React.ReactNode }) {
  return <Txt style={styles.placeholder}>{children}</Txt>;
}

export default function PrivacyPolicy() {
  const insets = useSafeAreaInsets();
  const router = useRouter();

  return (
    <View style={{ flex: 1, backgroundColor: colors.surface }}>
      <View style={[styles.header, { paddingTop: insets.top + spacing.sm }]}>
        <Pressable onPress={() => router.back()} hitSlop={12}>
          <Feather name="arrow-left" size={22} color={colors.onSurface} />
        </Pressable>
        <Txt display style={{ fontSize: fontSize.xl }}>Privacy Policy</Txt>
      </View>

      <ScrollView contentContainerStyle={{ padding: spacing.lg, paddingBottom: spacing["3xl"] }}>
        <Txt style={styles.updated}>Last updated: August 16, 2026</Txt>

        <P>
          This Privacy Policy describes how Cuddle ("Cuddle," "we," "us," or "our") collects, uses, shares,
          and protects information when you use the Cuddle mobile application and website (together, the
          "App"). Cuddle is a companion app for postpartum mothers, built around a household coordination
          feature ("Tag Team"), baby tracking, community features, and an AI chat companion.
        </P>
        <P>
          Please read this policy carefully. By using Cuddle, you agree to the practices described here. If
          you do not agree, please do not use the App.
        </P>

        <H2>1. Who We Are</H2>
        <P>
          Rohan Khanna, operating as an individual. (No registered mailing address yet, this should be added
          once one exists, as most state privacy laws expect one.)
        </P>
        <P>
          Cuddle is not a healthcare provider, and using the App does not create a doctor-patient or
          therapist-client relationship. Nothing in the App is a substitute for professional medical, mental
          health, or legal advice.
        </P>

        <H2>2. Information We Collect</H2>
        <P>We collect the following categories of information, some directly from you and some generated by your use of the App.</P>

        <Txt style={styles.h3}>2.1 Identity & Device Information</Txt>
        <P>
          A device identifier generated and stored on your device when you first open the App. This
          identifier, not an email or password, is how the App recognizes you; we do not currently require
          account creation with a username or password. If you enable Nearby, you may optionally provide an
          email address and phone number.
        </P>

        <Txt style={styles.h3}>2.2 Profile Information You Provide</Txt>
        <P>
          Your name, your baby's name, number of children, delivery type and date, feeding method, a
          description of your birth experience, your support level and initial mood, and any concerns you'd
          like the App to be aware of.
        </P>

        <Txt style={styles.h3}>2.3 Health & Wellbeing Information</Txt>
        <P>
          This is the most sensitive category of information the App collects. It includes daily mood
          check-ins, Recovery check-ins (including physical symptoms such as pain level and bleeding, which
          may generate an AI-written note if a combination may warrant medical attention), Edinburgh Postnatal
          Depression Scale (EPDS) responses, a standardized postpartum depression screening questionnaire,
          Dad's Corner partner/caregiver mood screening (PHQ-2) responses, and baby care logs (feed amounts and
          times, diaper changes, sleep duration). We do not use this information for advertising.
        </P>

        <Txt style={styles.h3}>2.4 Location Information (Nearby)</Txt>
        <P>
          If you enable Nearby, we collect an approximate location, which we deliberately distort before it
          is ever shown to other users: randomized and snapped to a coarse grid, so no one can see your
          precise or real-time location. We do not collect precise GPS location for any other feature. Nearby
          also lets you optionally share your ethnicity or cultural background, a cultural-matching
          preference, your due date or baby's age, and your timezone and language. Ethnicity/cultural
          background is sensitive personal information under many privacy laws; sharing it is entirely
          optional and used only for opt-in cultural community matching.
        </P>

        <Txt style={styles.h3}>2.5 Communications & Content You Create</Txt>
        <P>
          Messages you send to "Talk to Cuddle" (processed by a third-party AI provider, see Section 5);
          community posts and replies, which display your name or "Anonymous mama" and are visible to other
          users; photos you upload (such as Give & Share items, or invitations/appointment cards you scan so
          the App can extract event details using AI); messages you exchange with other users; and Meetup or
          event information you create or RSVP to.
        </P>

        <Txt style={styles.h3}>2.6 Household ("Tag Team") Information</Txt>
        <P>
          If you form a household with a partner or caregiver, caregiving coordination information, such as
          who is currently "on duty" and hours on duty, is shared between members of that household.
        </P>

        <Txt style={styles.h3}>2.7 Technical & Push Notification Information</Txt>
        <P>
          A push notification token, used only to deliver notifications you'd expect from the relevant
          feature (Tag Team nudges, event reminders, an SOS alert), plus standard technical information
          generated automatically by any internet request.
        </P>

        <Txt style={styles.h3}>2.8 Information From Other Users, About You</Txt>
        <P>
          If another user invites you to a Dinner Bell meal train or Meetup, or adds you as a household
          member, they may provide your name or contact information for that limited purpose only.
        </P>

        <H2>3. Information About Your Baby</H2>
        <P>
          The App is designed for use by parents and caregivers, not children. Information about your baby is
          provided by you and treated as part of your own account data. Cuddle does not knowingly collect
          information directly from children, and the App is not directed at or intended for use by children.
        </P>

        <H2>4. How We Use Your Information</H2>
        <P>We use the information above to operate the App's features; to power "Talk to Cuddle," including using recent self-reported patterns to make responses more relevant, never to diagnose, label, or clinically assess your mental state; to generate predictive estimates based on your own history or general age-based norms; to send notifications you'd reasonably expect; to maintain and secure the App; and to comply with legal obligations.</P>
        <P>
          We do not use your health, mood, or location information to serve you advertising, and we do not
          sell your personal information.
        </P>

        <H2>5. AI Processing and Third-Party Service Providers</H2>
        <P>
          Certain features send information to third-party providers who process it on our behalf: Anthropic
          (Claude AI) processes chat messages, pattern summaries, and scanned photos to generate responses and
          extract information. Cuddle uses Anthropic's commercial API (not Anthropic's consumer Claude.ai
          product). Under Anthropic's API/commercial terms, data is not used to train Anthropic's models by
          default, and API inputs/outputs are automatically deleted after 7 days.
        </P>
        <Placeholder>
          [Verify this remains accurate at anthropic.com before publishing. AI provider data policies can change.]
        </Placeholder>
        <P>
          We also use cloud hosting and database providers (currently Railway, MongoDB, and Vercel) and
          Expo/Apple push notification services, solely to operate and deliver the App.
        </P>

        <H2>6. How Information Is Shared With Other Users</H2>
        <P>
          Household/Tag Team members see shared caregiving status with each other. Community posts are
          visible to other App users. Meetup attendees can see each other's names. Give & Share and Dinner
          Bell involve limited information exchange with the specific users involved. Nearby shows an
          intentionally imprecise, randomized general area, never your exact location or identity unless you
          choose to share it directly. We do not otherwise share your personal information with third parties
          for their own marketing purposes, and we do not sell it.
        </P>

        <H2>7. Your Choices and Rights</H2>
        <P>You can view and update most profile information directly in the App. Nearby participation, including ethnicity/cultural sharing, is optional and can be disabled anytime. You can disable notifications at the device level anytime.</P>
        <P>
          You can permanently delete all of your data at any time directly from the App: go to Care → Delete
          My Data. This immediately and permanently removes your profile, logs, posts, and messages from our
          systems. If you are unable to use this feature, you may also request deletion by contacting us at
          rohankhanna1992@gmail.com, and we will delete your information within 14 days of a verified
          request, except where we are required to retain it by law.
        </P>
        <P>
          California residents have rights under the CCPA/CPRA to know what's collected, request deletion,
          and opt out of sale/sharing of personal information. We do not sell or share personal information
          as defined under the CCPA. Residents of other jurisdictions with their own privacy laws (e.g., GDPR)
          may have additional rights, including data portability. Contact us using Section 11 to exercise any
          of these rights.
        </P>

        <H2>8. Data Retention</H2>
        <P>
          We retain your information for as long as your device identifier is active and you continue using
          the App. If you request deletion, we will delete or de-identify your information within a
          reasonable time, except where retention is required by law or for legitimate purposes like fraud
          prevention.
        </P>

        <H2>9. Data Security</H2>
        <P>
          We use reasonable administrative and technical safeguards, including encrypted (HTTPS) connections
          between the App and our servers. No method of transmission or storage is 100% secure, and we cannot
          guarantee absolute security.
        </P>

        <H2>10. Children's Privacy</H2>
        <P>
          Cuddle is intended for adult parents and caregivers. It is not directed at or intended for use by
          children, and we do not knowingly collect personal information directly from children under 13 (or
          the relevant age in your jurisdiction). If you believe a child has provided us information directly,
          contact us so we can address it.
        </P>

        <H2>11. Contact Us</H2>
        <P>rohankhanna1992@gmail.com</P>

        <H2>12. Changes to This Policy</H2>
        <P>
          We may update this Privacy Policy from time to time. If we make material changes, we will update the
          "Last updated" date above, and where appropriate, provide additional notice within the App.
        </P>

        <Txt style={styles.disclaimer}>
          This Privacy Policy was prepared to accurately reflect Cuddle's actual data practices as of the date
          above. It is intended as a thorough starting point, not a substitute for review by a licensed
          attorney in your jurisdiction, particularly given the App's handling of health-related, location,
          and demographic information, and its use by consumers across potentially multiple states or
          countries.
        </Txt>
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  header: {
    flexDirection: "row",
    alignItems: "center",
    gap: spacing.md,
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  updated: { color: colors.muted, fontSize: fontSize.sm, marginBottom: spacing.md },
  h2: { fontSize: fontSize.lg, marginTop: spacing.lg, marginBottom: spacing.sm },
  h3: { fontSize: fontSize.base, marginTop: spacing.md, marginBottom: 4, color: colors.onSurface },
  p: { color: colors.onSurface, lineHeight: 21, marginBottom: spacing.sm },
  placeholder: {
    color: "#8A6D3B",
    backgroundColor: "#FBF3E0",
    borderRadius: 8,
    padding: spacing.sm,
    lineHeight: 20,
    marginBottom: spacing.sm,
    fontSize: fontSize.sm,
  },
  disclaimer: {
    color: colors.muted,
    fontSize: fontSize.sm,
    fontStyle: "italic",
    lineHeight: 19,
    marginTop: spacing.xl,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
});
